#!/usr/bin/env zsh

echo To: akkartik@gmail.com, mitultiwari@gmail.com
echo Subject: AARRR HackerStream metrics for yesterday
echo

export PATH=.:/app/hackerstream/log/yam:/app/local/0bin:/app/local/share/scripts:/app/local/share/scripts/Startup:/app/local/share/scripts/Data:$PATH:/usr/sbin
export RUBYLIB=/app/hackerstream/log/yam:$RUBYLIB
cd /app/hackerstream/log

wgrep() {
  grep -w $*
}

compute_date() {
  date +${2:-"%Y%m%d"} -d '-'$1' day'
}

percent() {
  printf "%.1f%%" $(($1.0/$2*100))
}

allprevsessions() {
  arg=${1:e}
  for file in development.log.*
  do
    if [ ${file:e} -lt $arg ]
    then
      echo $file
    fi
  done
}

prev7sessions() {
  for i in `seq 0 6`
  do
    echo development.log.*`compute_date $(($1+$i))`
  done
}

last -a -i |grep pts |column 10 |sort |uniq > my_ips
filter() {
  wgrep -f y.realips.$date |grep -vf my_ips
}

echo "select created_at from logins;" |mysql -u mtak -pmtak hackerstream_prod > y.logins
logins=`wc -l < y.logins`

echo "Date: Sessions -> More button -> Follow button -> Login || 7-day sessions -> 7-day returning || Unsubscribes"
stats() {
  date=`compute_date $1`

  if [ $date -gt "20110524" ] # that's when we added session cookie and username to STAT lines
  then
    grep "STAT" development.log.*$date |grep "/\.js" |column 4 |sort |uniq |grep -v "[a-z]" > y.realips.$date
    grep "STAT" development.log.*$date |grep "/\.js" |column 5 |sort |uniq |grep -v "[a-z]" >> y.realips.$date
  else
    grep "STAT" development.log.*$date |grep "/\.js" |column 2 |sort |uniq |grep -v "[a-z]" > y.realips.$date
    grep "STAT" development.log.*$date |grep "/\.js" |column 3 |sort |uniq |grep -v "[a-z]" >> y.realips.$date
  fi
  acq=`grep STAT development.log.*$date |filter |grep -v "/\.js" |column 5 |sort |uniq |wc -l`

  grep "Started" development.log.*$date |filter |grep -v "/\.js\|/?item\|/? " > y.clicks.$date
  clicks=`cat y.clicks.$date |column 5 |sort |uniq |wc -l`

  grep "Started.*/more" development.log.*$date |filter > y.more.$date
  more=`cat y.more.$date |column 5 |sort |uniq |wc -l`

  grep "Started.*/follow\>" development.log.*$date |filter > y.follow.$date
  follow=`cat y.follow.$date |column 5 |sort |uniq |wc -l`

  if [ $date -gt "20110525" ]
  then
    login=`grep STAT development.log.*$date |column 3 |sort |uniq |grep -v "^nil$\|akkartik\|mitultiwari" |wc -l`
  else
    login=0
  fi

  newlogins=`grep $(compute_date $1 "%Y-%m-%d") y.logins |wc -l`

  grep "Started.*/\.js" `prev7sessions $1` |perl -pwe 's/.*for |at |[0-9][0-9]:[0-9][0-9]:[0-9][0-9] //g' |sort |uniq > y.cohort.$date
  cohort=`cat y.cohort.$date |column 1 |sort |uniq |wc -l`
  returning=`cat y.cohort.$date |column 1 |sort |freq |grep -v " 1$" |wc -l`

  unsubscribes=`grep "Started.*/unsubscribe" development.log.*$date |column 5 |filter |sort |uniq |wc -l`

  echo "$date: $acq -> $more (`percent $more $acq`) -> $follow (`percent $follow $acq`) -> $login (`percent $login $acq`) || $cohort -> $returning (`percent $returning $cohort`) || $unsubscribes"
  grep $date milestones
}

for offset in `seq 1 14`
do
  stats $offset
done

echo
echo `wc -l < y.logins` logins total
